# Book settings
title: Lab in C&P (Fall 2021)
author: Todd Gureckis
logo: images/logo/artificialintelligence.svg

html:
  home_page_in_navbar: false

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

execute:
  execute_notebooks: off

parse:
  myst_extended_syntax: true

repository:
  url: https://github.com/brendenlake/lab-cognition-perception
  path_to_book: /
  branch: main

launch_buttons:
  notebook_interface: "classic"
  jupyterhub_url: "https://psychua-46-fall.rcnyu.org/"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  binderhub_url: ""
  # colab_url: "https://colab.research.google.com"
